### ISSUE TITLE
Transcode option

### ISSUE THREAD

**Issue by plimut** [vstavrinov/acestream-service#4] opened 2023-01-24 21:23 UTC
There is no sound in the mp4 file with ac3 sound in my browser, this is easily solved by adding the parameter transcode_ac3=1, for example:

```
http://127.0.0.1:6878/ace/getstream?id=acbfd1954084ffc68c65b0948485e5d0f82173e2&transcode_ac3 = 1
```

Is this possible at the moment?

**Comment by vstavrinov** [comment] 2023-01-26 14:48
Is possible what?

**Comment by plimut** [comment] 2023-01-27 07:22
Enable transcoding for AC3 streams in the acestream-engine docker.

transcode_ac3 = 1

**Comment by vstavrinov** [comment] 2023-01-27 16:09
1. You are writing to acestream-service repo not to acestream-engine. So it is not right place for the issue.
2. transcode_ac3 is playback parameter, not engine one. So there are nothing to do with engine.
3. acestream-service and acesteram_search as upstream, are using /ace/manifest.m3u8 endpoint and not /ace/getstream, so it is nothing to do with both. More over the engine itself return this endpoint by  search request. I never saw other endpoint in it's output. You can check this with with direct request to the engine
:
 `curl http://127.0.0.1:6878/search`
 .
You will see there infohash that is parameter for /ace/manifest.m3u8 endpoint. So it is out of scope of my code as it is engine itself.

4. I can't reproduce your problem as the request fails: 
```
curl -Lis http://127.0.0.1:6878/ace/getstream?id=acbfd1954084ffc68c65b0948485e5d0f82173e2          
HTTP/1.1 500 Internal Server Error
Server: BaseHTTP/0.6 Python/3.8.16
Date: Fri, 27 Jan 2023 15:22:52 GMT
Content-Type: text/plain
Content-Length: 22
Access-Control-Allow-Origin: *

failed to load content

```

P.S. If I am wrong as misunderstand something  (what is possible, as I never used endpoint  /ace/getstream), let me know with Your detail clarifications

**Comment by plimut** [comment] 2023-01-27 21:50
To better understand the problem, I made a playlist test:

#EXTM3U
#EXTINF:-1,1. TEST ORIGINAL AC3 (SNAP ACESTREAM ENGINE 3.1.49 (Linux x86)) WORKING-OK
http://127.0.0.1:6878/ace/manifest.m3u8?infohash=aeb2a969592f32d318e362601e3dfa9b51672039

#EXTINF:-1,2. TEST TRANSCODE DTS (SNAP ACESTREAM ENGINE 3.1.49 (Linux x86)) WORKING-OK
http://127.0.0.1:6878/ace/manifest.m3u8?infohash=aeb2a969592f32d318e362601e3dfa9b51672039&transcode_ac3=1

#EXTINF:-1,3. TEST ORIGINAL AC3 (ACESTREAM-SEARCH DOCKER (Linux x86)) WORKING-OK
http://127.0.0.1:8000/ace/manifest.m3u8?infohash=aeb2a969592f32d318e362601e3dfa9b51672039

#EXTINF:-1,4. TEST TRANSCODE DTS (ACESTREAM-SEARCH DOCKER (Linux x86)) ??? FAILED ???
http://127.0.0.1:8000/ace/manifest.m3u8?infohash=aeb2a969592f32d318e362601e3dfa9b51672039&transcode_ac3=1

Please try them and you will see that the 1,4 stream returns an error when adding a transcode parameter:
`access error: HTTP 500 error
http error: error: HTTP/1.1 500 Internal Server Error`
while the original engine is transcoding the audio.

Ideally, I see the acestream-service docker startup option --transcode-AC3 which will add &transcode_ac3=1 to the manifests URL.
This will allow the streams to be played in a web browser application such as iptvnator.

**Comment by vstavrinov** [comment] 2023-01-28 17:27
Thank You for explaining and  extra testing. I see the problem  and can reproduce it now. But ... the bad news is that Your proposition doesn't solve the problem because it's source isn't my code but acestream itself. Something similar I have have already stated earlier. 

The exact problem is the acestream version. You have run Your tests against 3.1.49 and I have got the same results with  android acestream 3.1.73.  But acestream-engine (and consequently acestream-service) is using acestream 3.1.75rc4. And there is the problem:

```
curl -Lis 'http://127.0.0.1:6878/ace/manifest.m3u8?infohash=aeb2a969592f32d318e362601e3dfa9b51672039&transcode_ac3=1'
HTTP/1.1 302 Found
Server: BaseHTTP/0.6 Python/3.8.16
Date: Sat, 28 Jan 2023 15:04:06 GMT
Location: http://127.0.0.1:6878/ace/m/aeb2a969592f32d318e362601e3dfa9b51672039/1b5337d0c8ad813197b506146d8d503d.m3u8
Access-Control-Allow-Origin: *

HTTP/1.1 500 Internal Server Error
Server: BaseHTTP/0.6 Python/3.8.16
Date: Sat, 28 Jan 2023 15:04:13 GMT
Content-Type: text/plain
Content-Length: 13
Access-Control-Allow-Origin: *

start timeout
```
There are no my code at all. It is pristine acestream only wrapped into container. You can reproduce this check if You run acestream-engine standalone: 

`docker run --name acestream-engine --detach --publish 6878:6878 vstavrinov/acestream-engine`

Fortunately there is good news: if You replace manifest.m3u with getstream the problem gone.  
```
curl -Lis 'http://127.0.0.1:6878/ace/getstream?infohash=aeb2a969592f32d318e362601e3dfa9b51672039&transcode_ac3=1'HTTP/1.1 302 Found
Server: BaseHTTP/0.6 Python/3.8.16
Date: Sat, 28 Jan 2023 15:04:28 GMT
Location: http://127.0.0.1:6878/ace/r/aeb2a969592f32d318e362601e3dfa9b51672039/1b5337d0c8ad813197b506146d8d503d
Access-Control-Allow-Origin: *

HTTP/1.1 302 Found
Server: BaseHTTP/0.6 Python/3.8.16
Date: Sat, 28 Jan 2023 15:04:29 GMT
Location: http://127.0.0.1:6878/content/aeb2a969592f32d318e362601e3dfa9b51672039/0.5307477323621013
Access-Control-Allow-Origin: *

HTTP/1.1 200 OK
Server: BaseHTTP/0.6 Python/3.8.16
Date: Sat, 28 Jan 2023 15:04:29 GMT
Connection: Keep-Alive
Keep-Alive: timeout=15, max=100
Content-Type: video/mp2t
Transfer-Encoding: chunked
```

What is the difference? The difference is format: HLS (manifest.m3u8) fails while MPEG-TS (getstream) works.
As I mentioned above, I have reproduced Your tests in chrome against acestream 3.1.73 and confirm that without transcode it is silent while transcode provide sound. But this done only for HLS option as I have such extension for chrome. But I can't run this test for MPEG-TS as chrome doesn't support it. So I expect You will run such tests.
If You discover there no problems with sound for MPEG-TS it is may be the way for solution.

As for transcode option for container I don't think this is good idea. As I accented in previous post transcode is playback parameter while container is running as service and stick all streams with particular playback option is not good. More over there are lot of others playback parameters and  litter container with all of them is certainly bad idea. 

The good idea is to send any playback parameters including format with search request. In response You get playlist either short or long with all desired options. So this task for other project i.e. [acestream_search](https://github.com/vstavrinov/acestream_search) . And I consider to work on it. May be I will set MPEG-TS format as default as it make sense for playback time slicing that not possible with HLS.

**Closed as completed** 2023-05-25 20:11 UTC
